version: '3.9'

services:
  user-database:
    image: mysql
    restart: on-failure
    networks:
      - central
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
    healthcheck:
      test: ["CMD","mysql","-h","localhost","-P","3306","-u","root","--password=root","-e","select 1","user"]
      interval: 5s
      timeout: 5s
      retries: 10

  user-service:
    image: shankhadeep05/containers-demo-user:latest
    networks: 
      - central
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://user-database:3306/user?useSSL=false&allowPublicKeyRetrieval=true 
    depends_on:
      user-database:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - "8081:8080"

  post-database:
    image: mysql
    restart: on-failure
    networks:
      - central
    ports:
      - "3367:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: post
    healthcheck:
      test: ["CMD","mysql","-h","localhost","-P","3306","-u","root","--password=root","-e","select 1","post"]
      interval: 5s
      timeout: 5s
      retries: 10    

  post-service:
    image: shankhadeep05/containers-demo-post:latest
    networks:
      - central
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://post-database:3306/post?useSSL=false&allowPublicKeyRetrieval=true 
      USER_URL: http://user-service:8081/user
    depends_on:
      post-database:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - "8082:8080"

networks:
  central:
